version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/protocol/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'RTann'
